// Builds the common-password list that the server rejects (M1/P1 design 3.4):
// server/internal/modules/identity/domain/common_passwords.txt.
// Usage: node tools/password-blocklist/build.mjs
//
// The source is NCSC's list of the 100,000 passwords most used in breaches,
// as SecLists keeps it at a pinned commit (cleaned of duplicate lines and bad
// encodings there). The script checks the download's SHA-256 before it uses
// it, keeps the entries that a password of 8–128 characters can equal once
// lowercased, and the core of every entry (lowercased, the non-letters
// trimmed from both ends, as domain/password.go's core does) of 5 characters
// or more: the server rejects a password whose core is listed, so Summer2024!
// fails on the core "summer" of an entry such as summer2019. It writes them
// deduplicated and sorted by UTF-8 bytes, the order Go's slices.BinarySearch
// needs. The Go unit test checks the same conditions on the output.
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const COMMIT = "1a7bb9127eca9e6ff2fc0301c597fe6e16a0cb56";
const PATH = "Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt";
const URL = `https://raw.githubusercontent.com/danielmiessler/SecLists/${COMMIT}/${PATH}`;
const SHA256 = "c2e5696882c603b76bb67a47ee970897e5a76fc4c3f5547abe3d0ca340c576e0";
const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../server/internal/modules/identity/domain/common_passwords.txt"
);

// The server's password lengths, in UTF-16 code units: a JavaScript string's length.
const MIN_LENGTH = 8;
const MAX_LENGTH = 128;
// The shortest core kept: shorter ones (love, blue) are parts of too many
// passwords that are not common.
const MIN_CORE_LENGTH = 5;

// core is domain/password.go's core of a lowercased entry: \p{L} is Go's
// unicode.IsLetter.
const core = (e) => e.replace(/^\P{L}+|\P{L}+$/gu, "");

const response = await fetch(URL);
if (!response.ok) {
  console.error(`${URL}: ${response.status} ${response.statusText}`);
  process.exit(1);
}
const data = Buffer.from(await response.arrayBuffer());
const sha256 = createHash("sha256").update(data).digest("hex");
if (sha256 !== SHA256) {
  console.error(`${URL}: SHA-256 is ${sha256}, want ${SHA256}`);
  process.exit(1);
}

const entries = new Set(
  data
    .toString("utf8")
    .split(/\r?\n/)
    .filter(Boolean)
    .map((s) => s.toLowerCase())
);
const cores = [...entries].map(core).filter((c) => c.length >= MIN_CORE_LENGTH && c.length <= MAX_LENGTH);
const kept = [
  ...new Set([...[...entries].filter((e) => e.length >= MIN_LENGTH && e.length <= MAX_LENGTH), ...cores]),
].toSorted((a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)));

const header = [
  "# Common passwords that Nerve Wiki rejects (M1/P1 design 3.4). Generated by",
  "# tools/password-blocklist/build.mjs; do not edit.",
  "#",
  "# Source: the NCSC list of the 100,000 passwords most used in breaches, from",
  "# Have I Been Pwned, as SecLists keeps it:",
  `# ${URL}`,
  `# SHA-256 ${SHA256}`,
  "# Contains public sector information licensed under the Open Government Licence v3.0:",
  "# https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
  "#",
  `# Kept: the entries of ${MIN_LENGTH}-${MAX_LENGTH} characters, and the core of every entry (its`,
  `# non-letters trimmed from both ends) of ${MIN_CORE_LENGTH} characters or more; lowercased, deduplicated.`,
  "# One per line, sorted by bytes, after the blank line below.",
];
writeFileSync(OUT, `${header.join("\n")}\n\n${kept.join("\n")}\n`);
console.log(`${entries.size} distinct lowercased entries, kept ${kept.length} in ${OUT}`);
