// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import "uuid"

// Defines values for FieldErrorCode.
const (
	FieldErrorCodeCommonPassword FieldErrorCode = "common_password"
	FieldErrorCodeDuplicate      FieldErrorCode = "duplicate"
	FieldErrorCodeInvalidFormat  FieldErrorCode = "invalid_format"
	FieldErrorCodeNotAllowed     FieldErrorCode = "not_allowed"
	FieldErrorCodeOutOfRange     FieldErrorCode = "out_of_range"
	FieldErrorCodeRequired       FieldErrorCode = "required"
	FieldErrorCodeTooLong        FieldErrorCode = "too_long"
	FieldErrorCodeTooShort       FieldErrorCode = "too_short"
)

// Valid indicates whether the value is a known member of the FieldErrorCode enum.
func (e FieldErrorCode) Valid() bool {
	switch e {
	case FieldErrorCodeCommonPassword:
		return true
	case FieldErrorCodeDuplicate:
		return true
	case FieldErrorCodeInvalidFormat:
		return true
	case FieldErrorCodeNotAllowed:
		return true
	case FieldErrorCodeOutOfRange:
		return true
	case FieldErrorCodeRequired:
		return true
	case FieldErrorCodeTooLong:
		return true
	case FieldErrorCodeTooShort:
		return true
	default:
		return false
	}
}

// FieldError One invalid field of a request. Clients show text looked up by `code`; `message` is an English explanation for developers. Must match httpserver.FieldError and the field codes of internal/shared.
type FieldError struct {
	// Code What is wrong with the field.
	Code FieldErrorCode `json:"code"`

	// Field The field's path in the request, e.g. title or properties.status. A path longer than 256 bytes is cut short and ends with `…`.
	Field   string `json:"field"`
	Message string `json:"message"`
}

// FieldErrorCode What is wrong with the field.
type FieldErrorCode string

// NextCursor The cursor of the next page; null on the last page.
type NextCursor = string

// Problem RFC 9457 problem details. `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it.
type Problem struct {
	// Code Stable error code. Platform codes have no prefix (bad_request, unauthorized, forbidden, not_found, payload_too_large, validation_failed, rate_limited, server_busy, internal_error, not_ready, storage_full); module codes are prefixed with the module that refuses, e.g. page.locked. Each operation lists the codes it can answer in x-problem-codes.
	Code string `json:"code"`

	// Detail What went wrong in this occurrence.
	Detail *string `json:"detail,omitempty"`

	// EndedBy Who ended the caller's edit session: page.edit_session_unlocked names the notebook's admin who unlocked it. No other code carries it.
	EndedBy *struct {
		DisplayName string    `json:"display_name"`
		UserID      uuid.UUID `json:"user_id"`
	} `json:"ended_by,omitempty"`

	// Errors The invalid fields of the request.
	Errors *[]FieldError `json:"errors,omitempty"`

	// Lock The edit lock page.locked names: the page locked and who holds it (the caller themself when they hold it elsewhere). No other code carries it.
	Lock *struct {
		DisplayName string    `json:"display_name"`
		PageID      uuid.UUID `json:"page_id"`
		UserID      uuid.UUID `json:"user_id"`
	} `json:"lock,omitempty"`

	// Locks The edit locks linking.pages_locked names, one a page: each page whose links a rename or move would write again and who edits it (the caller themself when they edit it). No other code carries it.
	Locks *[]struct {
		DisplayName string    `json:"display_name"`
		PageID      uuid.UUID `json:"page_id"`
		UserID      uuid.UUID `json:"user_id"`
	} `json:"locks,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title HTTP status phrase, e.g. "Not Found".
	Title string `json:"title"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int
