package app_test

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"log/slog"
	"net/netip"
	"strings"
	"testing"
	"time"
	"uuid"

	"github.com/open-nerve/NerveWiki/server/internal/modules/identity/app"
	"github.com/open-nerve/NerveWiki/server/internal/modules/identity/domain"
	"github.com/open-nerve/NerveWiki/server/internal/shared"
)

type registerFixture struct {
	store  *fakeStore
	tx     *fakeTx
	hasher *fakeHasher
	tokens *fakeTokens
	logs   *bytes.Buffer
	uc     *app.Register
}

func newRegister(policy app.SignupPolicy) *registerFixture {
	f := &registerFixture{store: &fakeStore{}, tx: &fakeTx{}, hasher: &fakeHasher{}, tokens: newFakeTokens(), logs: &bytes.Buffer{}}
	f.uc = app.NewRegister(app.RegisterDeps{
		Policy:   policy,
		Rules:    domain.NewPasswordRules(),
		Hasher:   f.hasher,
		Tx:       f.tx,
		Users:    f.store,
		Sessions: f.store,
		Issuance: testIssuance(f.tokens, fakeMAC{}),
		Clock:    fixedClock(testNow()),
		Logger:   slog.New(slog.NewJSONHandler(f.logs, nil)),
	})
	return f
}

// isV7 reports whether id is a version 7 UUID (RFC 9562 5.7): ids are
// generated by the application, time-ordered.
func isV7(id uuid.UUID) bool { return id[6]>>4 == 7 }

// assertNoSecret fails when logs hold secret in a spelling a log would
// give it: as is (a string), in hex of either case, or in either base64
// alphabet (slog's JSON handler writes a []byte as standard base64). The
// unpadded spellings also find the padded ones, which contain them.
func assertNoSecret(t *testing.T, logs, name string, secret []byte) {
	t.Helper()
	for _, spelling := range []string{
		string(secret),
		hex.EncodeToString(secret),
		strings.ToUpper(hex.EncodeToString(secret)),
		base64.RawStdEncoding.EncodeToString(secret),
		base64.RawURLEncoding.EncodeToString(secret),
	} {
		if strings.Contains(logs, spelling) {
			t.Errorf("logs hold the %s as %q:\n%s", name, spelling, logs)
		}
	}
}

func registration() app.RegisterInput {
	return app.RegisterInput{
		Email:     "  Alice@Corp.com ",
		Password:  "Tr0ub4dor&3",
		UserAgent: "agent\x00/1",
		IP:        netip.MustParseAddr("203.0.113.7"),
	}
}

func TestRegisterCreatesTheAccountAndSignsIn(t *testing.T) {
	f := newRegister(fixedPolicy{allow: true})
	in, now := registration(), testNow()

	tokens, err := f.uc.Execute(context.Background(), in)
	if err != nil {
		t.Fatal(err)
	}

	if f.tx.calls != 1 || len(f.store.outsideTx) != 0 {
		t.Errorf("transactions = %d, writes outside one = %q; want every write in one transaction", f.tx.calls, f.store.outsideTx)
	}
	if len(f.store.users) != 1 || len(f.store.sessions) != 1 {
		t.Fatalf("wrote %d users, %d sessions; want one each", len(f.store.users), len(f.store.sessions))
	}
	u, s := f.store.users[0], f.store.sessions[0]
	if u.Email != "alice@corp.com" || u.DisplayName != "alice" || u.PasswordHash != "hashed:Tr0ub4dor&3" || !u.Now.Equal(now) || !isV7(u.ID) {
		t.Errorf("user = %+v", u)
	}
	if s.UserID != u.ID || s.UserAgent != "agent/1" || s.IP != in.IP || !s.ExpiresAt.Equal(now.Add(720*time.Hour)) || !s.Now.Equal(now) || !isV7(s.ID) {
		t.Errorf("session = %+v", s)
	}

	// The refresh token: generation 0 of the new session, its secret's hash
	// stored, its tag the MAC of the first 52 bytes.
	raw, err := base64.RawURLEncoding.DecodeString(strings.TrimPrefix(tokens.RefreshToken, domain.RefreshTokenPrefix))
	if err != nil || len(raw) != 68 {
		t.Fatalf("refresh token %q: %d bytes, %v", tokens.RefreshToken, len(raw), err)
	}
	secretHash := sha256.Sum256(raw[20:52])
	if uuid.UUID(raw[0:16]) != s.ID || !bytes.Equal(raw[16:20], []byte{0, 0, 0, 0}) ||
		!bytes.Equal(s.TokenHash, secretHash[:]) || [16]byte(raw[52:68]) != (fakeMAC{}).Tag(raw[:52]) {
		t.Errorf("refresh token layout = % x, session %+v", raw, s)
	}
	if !tokens.RefreshExpiresAt.Equal(s.ExpiresAt) {
		t.Errorf("RefreshExpiresAt = %v, want the session's %v", tokens.RefreshExpiresAt, s.ExpiresAt)
	}

	want := app.AccessClaims{UserID: u.ID, SessionID: s.ID, ExpiresAt: accessExpiry()}
	if len(f.tokens.issued) != 1 || f.tokens.issued[0] != want || tokens.AccessToken != "access:"+s.ID.String() || tokens.AccessExpiresIn != 15*time.Minute {
		t.Errorf("access token %q expiring in %v, claims %+v; want claims %+v", tokens.AccessToken, tokens.AccessExpiresIn, f.tokens.issued, want)
	}
}

// Closed sign-up answers the same for every address: before validation,
// any lookup or any hash (M1/P1 design 3.7). A valid registration spends no
// hasher slot either.
func TestRegisterWhileSignupIsOff(t *testing.T) {
	for _, in := range []app.RegisterInput{{Email: "not an address", Password: "x"}, registration()} {
		f := newRegister(fixedPolicy{allow: false})

		_, err := f.uc.Execute(context.Background(), in)

		if !errors.Is(err, domain.ErrSignupDisabled) || f.hasher.calls != 0 || f.tx.calls != 0 {
			t.Errorf("Execute(%q) = %v, hashes %d, transactions %d; want identity.signup_disabled and nothing else", in.Email, err, f.hasher.calls, f.tx.calls)
		}
	}
}

func TestRegisterValidatesBeforeHashing(t *testing.T) {
	f := newRegister(fixedPolicy{allow: true})

	_, err := f.uc.Execute(context.Background(), app.RegisterInput{Email: "not an address", Password: "Password1!"})

	var se *shared.Error
	if !errors.As(err, &se) || se.Code != shared.CodeValidationFailed || len(se.Fields) != 2 || f.hasher.calls != 0 {
		t.Errorf("Execute() = %+v, hashes %d; want validation_failed on both fields and no hash", err, f.hasher.calls)
	}
}

func TestRegisterWithATakenAddress(t *testing.T) {
	f := newRegister(fixedPolicy{allow: true})
	f.store.createErr = domain.ErrEmailTaken

	_, err := f.uc.Execute(context.Background(), registration())

	if !errors.Is(err, domain.ErrEmailTaken) || len(f.store.sessions) != 0 {
		t.Errorf("Execute() = %v with %d sessions; want identity.email_taken and none", err, len(f.store.sessions))
	}
}

func TestRegisterWhenTheHasherIsBusy(t *testing.T) {
	f := newRegister(fixedPolicy{allow: true})
	f.hasher.err = shared.ServerBusy(time.Second)

	_, err := f.uc.Execute(context.Background(), registration())

	if !errors.Is(err, shared.ServerBusy(0)) || f.tx.calls != 0 {
		t.Errorf("Execute() = %v, transactions %d; want server_busy before any write", err, f.tx.calls)
	}
}

func TestRegisterPolicyFailureIsAnError(t *testing.T) {
	boom := errors.New("policy store down")
	f := newRegister(fixedPolicy{err: boom})

	if _, err := f.uc.Execute(context.Background(), registration()); !errors.Is(err, boom) {
		t.Errorf("Execute() = %v, want the policy's error", err)
	}
}

// The log names the account and the session; it never holds the address,
// the password, a token or a token's hash (M1 design 8).
func TestRegisterLogsTheAccountButNoSecret(t *testing.T) {
	f := newRegister(fixedPolicy{allow: true})
	in := registration()

	tokens, err := f.uc.Execute(context.Background(), in)
	if err != nil {
		t.Fatal(err)
	}

	logs := f.logs.String()
	if !strings.Contains(logs, `"msg":"account registered"`) || !strings.Contains(logs, f.store.users[0].ID.String()) ||
		!strings.Contains(logs, f.store.sessions[0].ID.String()) {
		t.Errorf("logs = %s, want the account registered with its user_id and session_id", logs)
	}
	assertNoSecret(t, logs, "address", []byte("alice@corp.com"))
	assertNoSecret(t, logs, "password", []byte(in.Password))
	assertNoSecret(t, logs, "password hash", []byte(f.store.users[0].PasswordHash))
	assertNoSecret(t, logs, "access token", []byte(tokens.AccessToken))
	assertNoSecret(t, logs, "refresh token", []byte(tokens.RefreshToken))
	assertNoSecret(t, logs, "token hash", f.store.sessions[0].TokenHash)
}
