/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe this instance
         * @description Reports the product, the build and the API version this instance runs. Public: needs no authentication.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One invalid field of a request. Clients show text looked up by `code`; `message` is an English explanation for developers. Must match httpserver.FieldError and the field codes of internal/shared. */
        FieldError: {
            /** @description The field's path in the request, e.g. title or properties.status. A path longer than 256 bytes is cut short and ends with `…`. */
            field: string;
            /**
             * @description What is wrong with the field.
             * @enum {string}
             */
            code: "required" | "invalid_format" | "too_short" | "too_long" | "out_of_range" | "not_allowed" | "duplicate";
            message: string;
        };
        /** @description RFC 9457 problem details. `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it. */
        Problem: {
            /** @description HTTP status code. */
            status: number;
            /** @description Stable error code. Platform codes have no prefix (bad_request, unauthorized, forbidden, not_found, payload_too_large, validation_failed, rate_limited, server_busy, internal_error, not_ready); module codes are prefixed with the module that refuses, e.g. page.locked. Each operation lists the codes it can answer in x-problem-codes. */
            code: string;
            /** @description HTTP status phrase, e.g. "Not Found". */
            title: string;
            /** @description What went wrong in this occurrence. */
            detail?: string;
            /** @description The invalid fields of the request. */
            errors?: components["schemas"]["FieldError"][];
        };
        InstanceInfo: {
            /**
             * @description Product name.
             * @example Nerve Wiki
             */
            product: string;
            /**
             * @description Product version of the running build.
             * @example 0.1.0-dev
             */
            version: string;
            /** @description Git revision of the running build; "unknown" when the build carries no VCS stamp. */
            commit: string;
            /**
             * @description Version of this HTTP API; every path starts with /api/{api_version}.
             * @enum {string}
             */
            api_version: "v0";
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details). */
        Problem: {
            headers: {
                /** @description Whole seconds to wait before trying again, rounded up; sent with rate_limited and server_busy. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type FieldError = components['schemas']['FieldError'];
export type Problem = components['schemas']['Problem'];
export type InstanceInfo = components['schemas']['InstanceInfo'];
export type ResponseProblem = components['responses']['Problem'];
export type $defs = Record<string, never>;
export interface operations {
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What this instance runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
