/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Creates an account and signs it in: the response holds a new session's tokens. While sign-up is off, a well-formed request answers identity.signup_disabled before the address or the password is looked at, so the answer never depends on whether the address is registered. The password needs 8–128 characters and must be neither a common password nor made of the address's local part. Sign-ups have a rate limit of their own, per client IP.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with an e-mail address and a password
         * @description Starts a new session and returns its tokens. An unknown address and a wrong password get the same identity.invalid_credentials; a deactivated account answers identity.account_deactivated only to the right password. Sign-ins have rate limits of their own: per client IP, and per client IP and address together.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe this instance
         * @description Reports the product, the build and the API version this instance runs, and whether it is open for sign-up. Public: needs no authentication.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @description The sign-in address; stored trimmed and in lower case.
             */
            email: string;
            password: string;
        };
        /** @description One invalid field of a request. Clients show text looked up by `code`; `message` is an English explanation for developers. Must match httpserver.FieldError and the field codes of internal/shared. */
        FieldError: {
            /** @description The field's path in the request, e.g. title or properties.status. A path longer than 256 bytes is cut short and ends with `…`. */
            field: string;
            /**
             * @description What is wrong with the field.
             * @enum {string}
             */
            code: "required" | "invalid_format" | "too_short" | "too_long" | "out_of_range" | "not_allowed" | "duplicate" | "common_password";
            message: string;
        };
        /** @description RFC 9457 problem details. `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it. */
        Problem: {
            /** @description HTTP status code. */
            status: number;
            /** @description Stable error code. Platform codes have no prefix (bad_request, unauthorized, forbidden, not_found, payload_too_large, validation_failed, rate_limited, server_busy, internal_error, not_ready); module codes are prefixed with the module that refuses, e.g. page.locked. Each operation lists the codes it can answer in x-problem-codes. */
            code: string;
            /** @description HTTP status phrase, e.g. "Not Found". */
            title: string;
            /** @description What went wrong in this occurrence. */
            detail?: string;
            /** @description The invalid fields of the request. */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description A session's tokens. Send access_token as "Authorization: Bearer"; access_token_expires_in counts from the response, so a client's clock does not matter. */
        AuthTokens: {
            /** @enum {string} */
            token_type: "Bearer";
            access_token: string;
            /** @description Seconds from this response until the access token expires. */
            access_token_expires_in: number;
            /** @description An opaque nwk_rt_ token. */
            refresh_token: string;
            /**
             * Format: date-time
             * @description When the session ends; refreshing never extends it.
             */
            refresh_token_expires_at: string;
        };
        LoginRequest: {
            /** @description The sign-in address, in any case, with or without surrounding blanks. It is not checked for form: an address no account has answers identity.invalid_credentials. */
            email: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @description The ids of the onboarding steps the account has completed; the web app defines the steps. */
            onboarding_steps: string[];
        };
        InstanceInfo: {
            /**
             * @description Product name.
             * @example Nerve Wiki
             */
            product: string;
            /**
             * @description Product version of the running build.
             * @example 0.1.0-dev
             */
            version: string;
            /** @description Git revision of the running build; "unknown" when the build carries no VCS stamp. */
            commit: string;
            /**
             * @description Version of this HTTP API; every path starts with /api/{api_version}.
             * @enum {string}
             */
            api_version: "v0";
            /** @description Whether anyone may register (auth.signup_enabled); when off, the server's administrator creates the accounts. */
            signup_enabled: boolean;
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details). */
        Problem: {
            headers: {
                /** @description Whole seconds to wait before trying again, rounded up; sent with rate_limited and server_busy. */
                "Retry-After"?: number;
                /** @description Sent with every 401 (RFC 9110 15.5.2): Bearer error="invalid_token" (RFC 6750 3) when the bearer token sent is refused before the operation runs, being invalid or expired; plain Bearer for every other 401. */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type RegisterRequest = components['schemas']['RegisterRequest'];
export type FieldError = components['schemas']['FieldError'];
export type Problem = components['schemas']['Problem'];
export type AuthTokens = components['schemas']['AuthTokens'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type User = components['schemas']['User'];
export type InstanceInfo = components['schemas']['InstanceInfo'];
export type ResponseProblem = components['responses']['Problem'];
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account exists and is signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The new session's tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What this instance runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
