/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Creates an account and signs it in: the response holds a new session's tokens. While sign-up is off, a well-formed request answers identity.signup_disabled before the address or the password is looked at, so the answer never depends on whether the address is registered. The password needs 8–128 characters and must be neither a common password nor made of the address's local part. Sign-ups have a rate limit of their own, per client IP.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with an e-mail address and a password
         * @description Starts a new session and returns its tokens. An unknown address and a wrong password get the same identity.invalid_credentials; a deactivated account answers identity.account_deactivated only to the right password. Sign-ins have rate limits of their own: per client IP, and per client IP and address together.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for the next pair
         * @description Returns new tokens of the same session and retires the refresh token sent: the next refresh uses the refresh_token of this response. The session's end, refresh_token_expires_at, never moves. Any refresh token but the current one of a session that has not ended answers identity.refresh_token_invalid; one this session issued before under the current signing key also ends the session, since someone else holds a copy of it. The server answers within a few seconds, before a client that waits 8 seconds gives up.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session of a refresh token
         * @description Ends the session when refresh_token is its current one; its access tokens stop working at once. Any other token changes nothing and gets the same answer, which tells nothing about the token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the caller's profile
         * @description Changes the fields sent and answers the account. A body without any field changes nothing. The address cannot change here: the server's administrator changes it.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v0/me/onboarding-steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a completed onboarding step
         * @description Adds the step to the account's onboarding_steps and answers the account; a step recorded already changes nothing. The web app defines the steps: the server checks the id's form, and records 32 steps at most.
         */
        post: operations["recordOnboardingStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the caller's password
         * @description Replaces the password once the current one is confirmed. Every other session of the account ends; the caller's own session goes on, and a caller with a personal access token ends them all. Personal access tokens keep working. Attempts have a rate limit of their own, per account.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate the caller's account
         * @description Deactivates the account: every session ends, and the personal access tokens stop working while it is inactive. Only the server's administrator can activate it again; sign-in then answers identity.account_deactivated. No password is asked for. The modules that keep the account's access elsewhere may refuse the deactivation with a code of their own, listed here.
         */
        post: operations["deactivateMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/me/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's personal access tokens
         * @description The caller's personal access tokens that are not revoked, expired ones too, newest first. The tokens themselves are never listed: only createApiToken answers one, once.
         */
        get: operations["listApiTokens"];
        put?: never;
        /**
         * Create a personal access token
         * @description Creates a personal access token of the caller and answers the token itself, this once. Sent as "Authorization: Bearer", it acts as the account in every operation until it expires or is revoked; it can create tokens itself. The caller's current password is asked for, whatever the credential: a refresh token that leaks cannot become a token that never expires. Attempts have a rate limit of their own, per account.
         */
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/api-tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a personal access token
         * @description Revokes one of the caller's tokens, which stops working at once; a token may revoke itself. A token that does not exist, is revoked already or belongs to another account is identity.api_token_not_found.
         */
        delete: operations["revokeApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe this instance
         * @description Reports the product, the build and the API version this instance runs, and whether it is open for sign-up. Public: needs no authentication.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @description The sign-in address; stored trimmed and in lower case.
             */
            email: string;
            password: string;
        };
        /** @description One invalid field of a request. Clients show text looked up by `code`; `message` is an English explanation for developers. Must match httpserver.FieldError and the field codes of internal/shared. */
        FieldError: {
            /** @description The field's path in the request, e.g. title or properties.status. A path longer than 256 bytes is cut short and ends with `…`. */
            field: string;
            /**
             * @description What is wrong with the field.
             * @enum {string}
             */
            code: "required" | "invalid_format" | "too_short" | "too_long" | "out_of_range" | "not_allowed" | "duplicate" | "common_password";
            message: string;
        };
        /** @description RFC 9457 problem details. `title` is the HTTP status phrase, `detail` explains this occurrence, and clients branch on `code`. Must match httpserver.Problem; the platform's contract test checks it. */
        Problem: {
            /** @description HTTP status code. */
            status: number;
            /** @description Stable error code. Platform codes have no prefix (bad_request, unauthorized, forbidden, not_found, payload_too_large, validation_failed, rate_limited, server_busy, internal_error, not_ready); module codes are prefixed with the module that refuses, e.g. page.locked. Each operation lists the codes it can answer in x-problem-codes. */
            code: string;
            /** @description HTTP status phrase, e.g. "Not Found". */
            title: string;
            /** @description What went wrong in this occurrence. */
            detail?: string;
            /** @description The invalid fields of the request. */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description A session's tokens. Send access_token as "Authorization: Bearer"; access_token_expires_in counts from the response, so a client's clock does not matter. When it expires, exchange refresh_token for the next pair at POST /api/v0/auth/refresh. */
        AuthTokens: {
            /** @enum {string} */
            token_type: "Bearer";
            access_token: string;
            /** @description Seconds from this response until the access token expires. */
            access_token_expires_in: number;
            /** @description An opaque nwk_rt_ token. */
            refresh_token: string;
            /**
             * Format: date-time
             * @description When the session ends; refreshing never extends it.
             */
            refresh_token_expires_at: string;
        };
        LoginRequest: {
            /** @description The sign-in address, in any case, with or without surrounding blanks. It is not checked for form: an address no account has answers identity.invalid_credentials. */
            email: string;
            password: string;
        };
        RefreshRequest: {
            /** @description The refresh_token of the session's last AuthTokens. */
            refresh_token: string;
        };
        LogoutRequest: {
            /** @description The refresh_token of the session's last AuthTokens. */
            refresh_token: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @description The ids of the onboarding steps the account has completed; the web app defines the steps. */
            onboarding_steps: string[];
        };
        UpdateMeRequest: {
            /** @description 1–100 characters after the surrounding blanks are trimmed, without control characters. */
            display_name?: string;
        };
        OnboardingStepRequest: {
            /** @description The step's id: a lower-case letter, then lower-case letters, digits and underscores, 32 characters at most. */
            step: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            /** @description 8–128 characters, neither a common password nor made of the address's local part. */
            new_password: string;
        };
        /** @description A personal access token as the list shows it. The token itself appears only in ApiTokenCreated. */
        ApiToken: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * Format: date-time
             * @description When the token stops working; null when it never does.
             */
            expires_at: string | null;
            /**
             * Format: date-time
             * @description When the token last authenticated a request, to the minute; null when it never has.
             */
            last_used_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ApiTokenList: {
            data: components["schemas"]["ApiToken"][];
        };
        ApiTokenCreate: {
            /** @description 1–100 characters after the surrounding blanks are trimmed, without control characters. */
            name: string;
            /**
             * Format: date-time
             * @description A time in the future; absent for a token that never expires.
             */
            expires_at?: string;
            current_password: string;
        };
        /** @description A new personal access token: the fields of ApiToken, and the token itself, which is shown this once and cannot be read again. */
        ApiTokenCreated: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * Format: date-time
             * @description When the token stops working; null when it never does.
             */
            expires_at: string | null;
            /**
             * Format: date-time
             * @description Null; the token has not been used yet.
             */
            last_used_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description The token, nwk_pat_ and 43 more characters. */
            token: string;
        };
        InstanceInfo: {
            /**
             * @description Product name.
             * @example Nerve Wiki
             */
            product: string;
            /**
             * @description Product version of the running build.
             * @example 0.1.0-dev
             */
            version: string;
            /** @description Git revision of the running build; "unknown" when the build carries no VCS stamp. */
            commit: string;
            /**
             * @description Version of this HTTP API; every path starts with /api/{api_version}.
             * @enum {string}
             */
            api_version: "v0";
            /** @description Whether anyone may register (auth.signup_enabled); when off, the server's administrator creates the accounts. */
            signup_enabled: boolean;
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details). */
        Problem: {
            headers: {
                /** @description Whole seconds to wait before trying again, rounded up; sent with rate_limited and server_busy. */
                "Retry-After"?: number;
                /** @description Sent with every 401 (RFC 9110 15.5.2): Bearer error="invalid_token" (RFC 6750 3) when the bearer token sent is refused before the operation runs, being invalid or expired; plain Bearer for every other 401, including a credential that the operation finds revoked while it runs. */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type RegisterRequest = components['schemas']['RegisterRequest'];
export type FieldError = components['schemas']['FieldError'];
export type Problem = components['schemas']['Problem'];
export type AuthTokens = components['schemas']['AuthTokens'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type RefreshRequest = components['schemas']['RefreshRequest'];
export type LogoutRequest = components['schemas']['LogoutRequest'];
export type User = components['schemas']['User'];
export type UpdateMeRequest = components['schemas']['UpdateMeRequest'];
export type OnboardingStepRequest = components['schemas']['OnboardingStepRequest'];
export type ChangePasswordRequest = components['schemas']['ChangePasswordRequest'];
export type ApiToken = components['schemas']['ApiToken'];
export type ApiTokenList = components['schemas']['ApiTokenList'];
export type ApiTokenCreate = components['schemas']['ApiTokenCreate'];
export type ApiTokenCreated = components['schemas']['ApiTokenCreated'];
export type InstanceInfo = components['schemas']['InstanceInfo'];
export type ResponseProblem = components['responses']['Problem'];
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account exists and is signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The new session's tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The session's next tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Done, whatever the token was. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The caller's account, changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    recordOnboardingStep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingStepRequest"];
            };
        };
        responses: {
            /** @description The caller's account, with the step. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The password is changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    deactivateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account is deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listApiTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreate"];
            };
        };
        responses: {
            /** @description The new token, with the token itself. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreated"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What this instance runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
